// @ts-check
import {shouldFilterDocsInProduction} from './src/lib/docsPublication.mjs';

const includeUnfinishedDocs = !shouldFilterDocsInProduction();

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Начало работы',
      link: { type: 'doc', id: 'getting-started/getting-started' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Из чего состоит редактор',
      link: { type: 'doc', id: 'concepts/concepts' },
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'Сценарии',
      link: { type: 'doc', id: 'workflows/workflows' },
      items: [{ type: 'autogenerated', dirName: 'workflows' }],
    },
    {
      type: 'category',
      label: 'Справочник',
      link: { type: 'doc', id: 'reference/reference' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    ...(includeUnfinishedDocs
      ? [
          {
            type: 'category',
            label: 'Архив старой структуры',
            link: { type: 'doc', id: 'legacy/legacy' },
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'legacy' }],
          },
        ]
      : []),
  ],
};
export default sidebars;
