// @ts-check
import {shouldFilterDocsInProduction} from './src/lib/docsPublication.mjs';

const includeUnfinishedDocs = !shouldFilterDocsInProduction();

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: /** @type {import('@docusaurus/plugin-content-docs/lib/sidebars/types.js').SidebarItemConfig[]} */ ([
    {
      type: 'category',
      label: 'Начать',
      link: {type: 'doc', id: 'getting-started/getting-started'},
      items: [],
    },
    {
      type: 'category',
      label: 'Подготовить выкройку',
      link: {type: 'doc', id: 'concepts/pattern-concept'},
      items: [
        {type: 'doc', id: 'pattern-work/draw-and-edit-pattern'},
        {type: 'doc', id: 'pattern-work/create-pattern-from-measurements'},
        {type: 'doc', id: 'pattern-work/pattern-templates-catalog'},
        {type: 'doc', id: 'pattern-work/prepare-pattern-for-knitting'},
      ],
    },
    {
      type: 'category',
      label: 'Создать схему вязания',
      link: {type: 'doc', id: 'concepts/knitting-concept'},
      items: [
        {type: 'doc', id: 'knitting-work/draw-swatch-or-chart'},
        {
          type: 'category',
          label: 'Узоры',
          link: {type: 'doc', id: 'knitting-work/choose-or-create-pattern'},
          items: [
            ...(includeUnfinishedDocs
              ? [
                  {type: 'doc', id: 'knitting-work/choose-pattern-from-library'},
                  {type: 'doc', id: 'knitting-work/generate-pattern'},
                  {type: 'doc', id: 'knitting-work/create-jacquard-pattern'},
                  {type: 'doc', id: 'knitting-work/construct-pattern'},
                  {type: 'doc', id: 'knitting-work/create-pattern-from-selection'},
                ]
              : []),
          ],
        },
        {
          type: 'category',
          label: 'Пряжа и плотность',
          items: [
            {type: 'doc', id: 'concepts/yarn-concept', label: 'Выбрать пряжу'},
            {type: 'doc', id: 'concepts/gauge-concept', label: 'Настроить плотность'},
            {type: 'autogenerated', dirName: 'workflows/yarn-and-gauge'},
          ],
        },
        {
          type: 'category',
          label: 'Рассчитать по выкройке',
          link: {type: 'doc', id: 'workflows/pattern-to-knitting/calculate-from-pattern'},
          items: [],
        },
        {type: 'doc', id: 'knitting-work/add-color-pattern'},
        {type: 'doc', id: 'knitting-work/combine-patterns-in-piece'},
        {type: 'doc', id: 'knitting-work/check-and-adjust-chart'},
      ],
    },
    {
      type: 'category',
      label: 'Вязать',
      link: {type: 'doc', id: 'concepts/knitting-mode-concept'},
      items: [
        {type: 'doc', id: 'knitting-use/estimate-yarn-usage'},
        {type: 'doc', id: 'knitting-use/track-knitting-progress'},
        {type: 'doc', id: 'knitting-use/read-row-instructions'},
      ],
    },
    {
      type: 'category',
      label: 'Работать с проектом',
      items: [
        {type: 'doc', id: 'work-with-project/create-project'},
        {type: 'doc', id: 'work-with-project/save-project'},
        {type: 'doc', id: 'work-with-project/open-project'},
        {type: 'doc', id: 'work-with-project/share-project'},
        {type: 'doc', id: 'work-with-project/use-project-on-mobile'},
        {type: 'doc', id: 'work-with-project/organize-project'},
        {type: 'doc', id: 'work-with-project/create-project-collage'},
      ],
    },
  ]),
};
export default sidebars;
